
CREATE TABLE GRACZ(
LOGIN VARCHAR(20),
HASLO VARCHAR(20),
CONSTRAINT GRACZ_PK PRIMARY KEY (LOGIN)
);
/
CREATE TABLE GRA (
ID NUMBER(6) ,
ID_GRACZ1 VARCHAR(20),
ID_GRACZ2 VARCHAR(20),
DATA_ROZPOCZECIA DATE ,
DATA_ZAKONCZENIA DATE,
CONSTRAINT GRA_PK PRIMARY KEY (ID),
CONSTRAINT GRA_GRACZ1_FK FOREIGN KEY (ID_GRACZ1) REFERENCES GRACZ(LOGIN),
CONSTRAINT GRA_GRACZ2_FK FOREIGN KEY (ID_GRACZ2) REFERENCES GRACZ(LOGIN)
);
/
CREATE TABLE FIGURA(
ID NUMBER(6),
NAZWA VARCHAR(20),
CONSTRAINT FTYP_PK PRIMARY KEY (ID)
);
/
CREATE TABLE PIONKI_W_GRZE(
ID NUMBER(6),
ID_GRA NUMBER(6),
ID_GRACZ VARCHAR(20),
ID_FIGURA NUMBER(6),
X NUMBER(2),
Y NUMBER(2),
DATA_POSTAWIENIA DATE,
TYP varchar2(10) default 'ruch' constraint typ_check
  CHECK (typ IN ('ruch','zbicie')),
id_figury_gracza number(3),
CONSTRAINT PWG_PK PRIMARY KEY(ID),
CONSTRAINT PWG_GRA_FK FOREIGN KEY(ID_GRA) REFERENCES GRA(ID),
CONSTRAINT PWG_GRACZ_FK FOREIGN KEY(ID_GRACZ) REFERENCES GRACZ(LOGIN),
CONSTRAINT PWG_PIONEK_FK FOREIGN KEY(ID_FIGURA) REFERENCES FIGURA(ID)
);
/
create sequence pwg_seq start with 1 increment by 1;
/
create trigger pwg_binsert before insert on pionki_w_grze for each row
begin
  if :new.id is null then :new.id := pwg_seq.nextval;
  end if;
end;
/